### ISSUE TITLE
"org.quartz.SchedulerConfigException: DataSource name not set" even when jdbcStore is set to false

### ISSUE THREAD

**Issue by vijeetgv** [grails3-plugins/quartz#19]
Just upgraded to Grails 2.4.3 & also upgraded quartz to 1.0.2 & getting this exception. The configuration seems fine:

```
quartz {
    jdbcStore = false
    autoStartup = true
}
```

but upon running the application it throws down this:

```
Caused by: org.quartz.SchedulerConfigException: DataSource name not set.
    at org.quartz.impl.jdbcjobstore.JobStoreSupport.initialize(JobStoreSupport.java:638)
    at org.quartz.impl.jdbcjobstore.JobStoreTX.initialize(JobStoreTX.java:57)
    at org.quartz.impl.StdSchedulerFactory.instantiate(StdSchedulerFactory.java:1333)
    at org.quartz.impl.StdSchedulerFactory.getScheduler(StdSchedulerFactory.java:1519)
    at org.springframework.scheduling.quartz.SchedulerFactoryBean.createScheduler(SchedulerFactoryBean.java:597)
    at org.springframework.scheduling.quartz.SchedulerFactoryBean.afterPropertiesSet(SchedulerFactoryBean.java:480)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1633)
    at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1570)
    ... 25 more
```

**Comment by vijeetgv** [comment]
Sorry this bug is in Grails 2 version of plugin. Will open an issue there.
