### ISSUE TITLE
Quartz Plugin not working in 3.0 RC3

### ISSUE THREAD

**Issue by volnei** [grails3-plugins/quartz#3]
After add this plugin as dependency the project does not start with the follow error

```
Exception in thread "main" org.springframework.beans.factory.BeanCreationException: Error creating bean with n
ame 'grailsApplicationPostProcessor' defined in cursiva.Application: Bean instantiation via factory method fai
led; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.b
oot.config.GrailsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; n
ested exception is org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class
 grails.plugins.quartz.JobManagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: Invocatio
nTargetException                                                                                             o
rg.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grailsApplicationPostPr
ocessor' defined in cursiva.Application: Bean instantiation via factory method failed; nested exception is org
.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.GrailsApplication
PostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exception is org.grail
s.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class grails.plugins.quartz.JobMa
nagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetException

        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(Constru
ctorResolver.java:599) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(Constru
ctorResolver.java:599)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactor
yMethod(AbstractAutowireCapableBeanFactory.java:1119) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactor
yMethod(AbstractAutowireCapableBeanFactory.java:1119)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(Abs
tractAutowireCapableBeanFactory.java:1014)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractA
utowireCapableBeanFactory.java:504)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAut
owireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:
303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingleto
nBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:29
9)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)

        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcesso
rs(PostProcessorRegistrationDelegate.java:116)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(Abst
ractApplicationContext.java:606)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.j
ava:462)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(Abs
tractAutowireCapableBeanFactory.java:1014) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractA
utowireCapableBeanFactory.java:504) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAut
owireCapableBeanFactory.java:476) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:
303) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingleto
nBeanRegistry.java:230) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbsanFactory.doGetBean(AbstractBeanFactory.java:299) ~[sp
ring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
 ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcesso
rs(PostProcessorRegistrationDelegate.java:116) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(Abst
ractApplicationContext.java:606) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.j
ava:462) ~[spring-context-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicat
ionContext.java:118) ~[spring-boot-1.2.2.RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686) ~[spring-boot-1.2.2.
RELEASE.jar:1.2.2.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320) ~[spring-boot-1.2.2.RELE
ASE.jar:1.2.2.RELEASE]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:49) [grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:254) [grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:243) [grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicat
ionContext.java:118)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]

        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40
]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:686)
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) [
springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.codehaus.groovy.reflectiodMethod.invoke(CachedMethod.java:90) [groovy-2.4.3.jar:2.4.3]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:320)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324) [groovy-2.4.3.jar:2.4.3]
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43) [gro
ovy-2.4.3.jar:2.4.3]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:49)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88) [groov
y-2.4.3.jar:2.4.3]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:254)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45) [groovy-2.4.3
.jar:2.4.3]
        at grails.boot.GrailsApp.run(GrailsApp.groovy:243)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110) [groovy-2.4.3
.jar:2.4.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122) [groovy-2.4.3
.jar:2.4.3]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:90)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:324)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.invoke(StaticMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.StaticMetaMethodSite.call(StaticMetaMethodSite.java:88)
        at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:45)
        at cursiva.Application.main(Application.groovy:8) [main/:na]
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:110)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.Gra
ilsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exceptio
n is org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class grails.plugin
s.quartz.JobManagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetExcepti
on
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiati
onStrategy.java:189) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(Constru
ctorResolver.java:588) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        ... 30 common frames omitted
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:122)
Caused by: org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class grails.
plugins.quartz.JobManagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetE
xception
        at cursiva.Application.main(Application.groovy:8)
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:169) ~[grails-core-
3.0.0.RC3.jar:3.0.0.RC3]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [grails.boot.config.Gra
ilsApplicationPostProcessor]: Factory method 'grailsApplicationPostProcessor' threw exception; nested exceptio
n is org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class grails.plugin
s.quartz.JobManagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetExcepti
on
        at grails.core.DefaultGrailsApplication.addArte at org.springframework.beans.factory.support.SimpleIns
tantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)                                         f
aultGrailsApplication.java:784) ~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:778) ~[gr
ails-core-3.0.0.RC3.jar:3.0.0.RC3]

        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:763) ~[gr
ails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(Constru
ctorResolver.java:588)
        at org.grails.plugins.AbstractGrailsPluginManager.registerProvidedArtefacts(AbstractGrailsPluginManage
r.java:308) ~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        ... 30 more
        at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplica
tionPostProcessor.groovy:98) ~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
Caused by: org.grails.core.exceptions.GrailsRuntimeException: Error instantiated artefact class [class grails.
plugins.quartz.JobManagerService] of type [class org.grails.core.DefaultGrailsServiceClass]: InvocationTargetE
xception
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:169)
        at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPost
Processor.groovy:88) ~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at grails.core.DefaultGrailsApplication.addArtefact(DefaultGrailsApplication.java:784)
        at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:76)
~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.g
roovy:38) ~[grails-core-3.0.0.RC3.jar:3.0.0.RC3]
        at cursiva.Application.grailsApplicationPostProcessor(Application.groovy) [main/:na]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_40]
        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:778)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_40
]
        at grails.core.DefaultGrailsApplication.addOverridableArtefact(DefaultGrailsApplication.java:763)
        at java.lang.reflect.Method.invoke(Method.java:497) ~[na:1.8.0_40]
        at org.grails.plugins.AbstractGrailsPluginManager.registerProvidedArtefacts(AbstractGrailsPluginManage
r.java:308)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270) [
springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at grails.boot.config.GrailsApplicationPostProcessor.performGrailsInitializationSequence(GrailsApplica
tionPostProcessor.groovy:98)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiati
onStrategy.java:162) ~[spring-beans-4.1.6.RELEASE.jar:4.1.6.RELEASE]
        at grails.boot.config.GrailsApplicationPostProcessor.initializeGrailsApplication(GrailsApplicationPost
Processor.groovy:88)
        ... 31 common frames omitted
        at grails.boot.config.GrailsApplicationPostProcessor.<init>(GrailsApplicationPostProcessor.groovy:76)
Caused by: java.lang.reflect.InvocationTargetException: null
        at grails.boot.config.GrailsAutoConfiguration.grailsApplicationPostProcessor(GrailsAutoConfiguration.g
roovy:38)
        at sun.reflect.NativeConstructorAccessorImpl.nnce0(Native Method) ~[na:1.8.0_40]
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1
.8.0_40]
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
) ~[na:1.8.0_40]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422) ~[na:1.8.0_40]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.ja
va:1002) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:160) ~[grails-core-
3.0.0.RC3.jar:3.0.0.RC3]
        ... 46 common frames omitted
Caused by: java.lang.NoClassDefFoundError: reactor/bus/Observable
        at java.lang.Class.getDeclaredMethods0(Native Method) ~[na:1.8.0_40]
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701) ~[na:1.8.0_40]
        at java.lang.Class.getDeclaredMethods(Class.java:1975) ~[na:1.8.0_40]
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlClassGetDeclaredMethods(ReflectiveInterceptor.ja
va:145) [springloaded-1.2.3.RELEASE.jar:1.2.3.RELEASE]
        at org.grails.core.util.ClassPropertyFetcher.init(ClassPropertyFetcher.java:185) ~[grails-core-3.0.0.R
C3.jar:3.0.0.RC3]
        at org.grails.core.util.ClassPropertyFetcher.<init>(ClassPropertyFetcher.java:95) ~[grails-core-3.0.0.
RC3.jar:3.0.0.RC3]
        at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:86) ~[grails-core-3.0.
0.RC3.jar:3.0.0.RC3]
        at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:61) ~[grails-core-3.0.
0.RC3.jar:3.0.0.RC3]
        at org.grails.core.AbstractGrailsClass.<init>(AbstractGrailsClass.java:91) ~[grails-core-3.0.0.RC3.jar
:3.0.0.RC3]
        at org.grails.core.AbstractInjectableGrailsClass.<init>(AbstractInjectableGrailsClass.java:31) ~[grail
s-core-3.0.0.RC3.jar:3.0.0.RC3]
        at org.grails.core.DefaultGrailsServiceClass.<init>(DefaultGrailsServiceClass.java:32) ~[grails-core-3
.0.0.RC3.jar:3.0.0.RC3]
        ... 52 common frames omitted
Caused by: java.lang.ClassNotFoundException: reactor.bus.Observable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[na:1.8.0_40]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[na:1.8.0_40]
        at cursiva.Application.grailsApplicationPostProcessor(Application.groovy)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[na:1.8.0_40]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        ... 63 common frames omitted
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrMethodInvoke(ReflectiveInterceptor.java:1270)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiati
onStrategy.java:162)
        ... 31 more
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstrucssorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45
)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlrConstructorNewInstance(ReflectiveInterceptor.ja
va:1002)
        at grails.core.ArtefactHandlerAdapter.newArtefactClass(ArtefactHandlerAdapter.java:160)
        ... 46 more
Caused by: java.lang.NoClassDefFoundError: reactor/bus/Observable
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Class.java:2701)
        at java.lang.Class.getDeclaredMethods(Class.java:1975)
        at org.springsource.loaded.ri.ReflectiveInterceptor.jlClassGetDeclaredMethods(ReflectiveInterceptor.ja
va:145)
        at org.grails.core.util.ClassPropertyFetcher.init(ClassPropertyFetcher.java:185)
        at org.grails.core.util.ClassPropertyFetcher.<init>(ClassPropertyFetcher.java:95)
        at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:86)
        at org.grails.core.util.ClassPropertyFetcher.forClass(ClassPropertyFetcher.java:61)
        at org.grails.core.AbstractGrailsClass.<init>(AbstractGrailsClass.java:91)
        at org.grails.core.AbstractInjectableGrailsClass.<init>(AbstractInjectableGrailsClass.java:31)
        at org.grails.core.DefaultGrailsServiceClass.<init>(DefaultGrailsServiceClass.java:32)
        ... 52 more
Caused by: java.lang.ClassNotFoundException: reactor.bus.Observable
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 63 more
```

**Comment by jeffscottbrown** [comment]
Will take a look.  Thanks for the feedback.

**Comment by jeffscottbrown** [comment]
I think 2.0.0.M4 of the plugin should be compatible with Grails 3.0.0 and Grails 3.0.0.RC3 now.  Can you confirm @volnei ?

**Comment by volnei** [comment]
Yes @jeffbrown 

Thank you for your quick response and solution.

**Comment by sphinks** [comment]
Hello. I have the same error, but I use such config:

Grails Version: 3.0.0.RC1
Groovy Version: 2.4.1
JVM Version: 1.8.0_40

quartz plugin: compile "org.grails.plugins:quartz:2.0.0.M4"

Shoild I try to move to RC3?

**Comment by jeffscottbrown** [comment]
@sphinks I don't expect 2.0.0.M4 of the plugin to be compatible with RC1.  I believe it is compatible with RC3, 3.0.0 and 3.0.1.  If you are going to upgrade, why would you upgrade to RC3 at this point?  3.0.0 and 3.0.1 have been released.

**Comment by sphinks** [comment]
@jeffbrown you are right. Confirm that there is no problems with grails 3.0.1.
Thanks.
